import { createContext, useContext, useState, useCallback, type ReactNode } from 'react';
import type { Language } from '@/types';

type TranslationDict = Record<string, string>;

const EN: TranslationDict = {
  app_title: 'Temple Fund & Devotee Bulletin',
  lang_en: 'EN',
  lang_ta: 'தமிழ்',
  lang_bm: 'BM',
  contribute_now: 'Contribute Now',
  admin_dashboard: 'Admin Dashboard',
  admin_login: 'Admin Login',
  admin_logout: 'Logout',
  admin_tab_login: 'Login',
  admin_tab_register: 'Register',
  admin_email_placeholder: 'Enter your email',
  admin_password_placeholder: 'Enter your password',
  admin_confirm_password_placeholder: 'Confirm your password',
  admin_invalid_credentials: 'Sign in failed. Please check your credentials.',
  admin_forgot_password: 'Forgot Password?',
  admin_show_password: 'Show',
  admin_hide_password: 'Hide',
  admin_register_success_message: 'Account created. Check your email for confirmation, then an existing admin must approve your access.',
  auth_forgot_success: 'If an account exists, a password reset link has been sent.',
  auth_user_not_found: 'No account found with this email.',
  auth_invalid_credentials: 'Invalid email or password.',
  auth_email_not_confirmed: 'Please confirm your email address first.',
  auth_not_approved: 'Your admin account has not been approved yet.',
  admin_pending_approval_title: 'Pending Admin Approval',
  admin_pending_approval_body: 'Your admin account has been created but requires approval from an existing administrator. Please wait to be approved.',
  admin_submissions_title: 'Devotee Submissions',
  admin_event: 'Event',
  admin_name: 'Name',
  admin_whatsapp: 'WhatsApp',
  admin_email: 'Email',
  admin_amount: 'Amount (RM)',
  admin_proof: 'Receipt',
  admin_status: 'Status',
  admin_actions: 'Actions',
  admin_approve: 'Approve',
  admin_reject: 'Reject',
  admin_whatsapp_btn: 'Send WhatsApp',
  admin_no_submissions: 'No submissions yet.',
  admin_no_submissions_hint: 'Registrations from devotees will appear here once submitted.',
  admin_table_loading: 'Loading submissions...',
  admin_refresh: 'Refresh',
  admin_export_csv: 'Export CSV',
  admin_search_placeholder: 'Search name, WhatsApp or email…',
  admin_filter_all: 'All',
  admin_no_results: 'No registrations match your search.',
  admin_stat_total: 'Total',
  admin_stat_pending: 'Pending',
  admin_stat_approved: 'Approved',
  admin_stat_rejected: 'Rejected',
  admin_stat_collected: 'Collected',
  admin_stat_awaiting: 'Awaiting',
  admin_events_title: 'Events',
  admin_natchatram: 'Natchatram',
  admin_rasi: 'Rasi',
  admin_family: 'Family Members',
  admin_materials: 'Sponsored Materials',
  admin_submitted_at: 'Submitted',
  admin_ref: 'Ref',
  admin_view_details: 'Details',
  admin_hide_details: 'Hide',
  admin_mark_pending: 'Mark Pending',
  admin_copy_wa: 'Copy WhatsApp',
  admin_copied: 'Copied!',
  admin_none_provided: '—',
  events_admin_title: 'Manage Events',
  events_admin_new: 'New Event',
  events_admin_edit: 'Edit',
  events_admin_delete: 'Delete',
  events_admin_delete_confirm: 'Delete this event? This cannot be undone.',
  events_admin_name: 'Event Name',
  events_admin_cost: 'Cost per Pax (RM)',
  events_admin_time: 'Abhishegam Time',
  events_admin_notes: 'Special Notes',
  events_admin_poster: 'Poster Image URL',
  events_admin_status: 'Status',
  events_admin_carousel: 'Show in Carousel',
  events_admin_save: 'Save Event',
  events_admin_cancel: 'Cancel',
  events_admin_saved: 'Event saved.',
  events_admin_deleted: 'Event deleted.',
  events_admin_error: 'Could not save event. Please try again.',
  events_admin_none: 'No events yet. Create one to get started.',
  events_admin_required: 'Event name is required.',
  step1_title: 'Step 1: Payment Details',
  step2_title: 'Step 2: Registration',
  step3_title: 'Step 3: Confirmation',
  step_short_1: 'Payment',
  step_short_2: 'Register',
  step_short_3: 'Done',
  contribute_close: 'Close Form',
  contact_name: 'Full Name',
  contact_name_placeholder: 'Enter your full name',
  contact_whatsapp: 'WhatsApp Number',
  contact_whatsapp_placeholder: 'e.g. 0123456789',
  contact_email: 'Email',
  contact_email_placeholder: 'you@example.com',
  contact_natchatram: 'Natchatram (Birth Star)',
  contact_rasi: 'Rasi (Zodiac)',
  step1_bank_label: 'Bank',
  step1_account_label: 'Account Name',
  step1_number_label: 'Account Number',
  step1_cost_label: 'Cost Per Person',
  step1_scan_qr: 'Scan QR Code to Pay',
  step2_next: 'Proceed to Registration',
  step2_submit: 'Submit Registration',
  step2_upload_receipt: 'Upload Payment Receipt',
  step2_drag_drop: 'Drag & drop or click to upload',
  step2_file_selected: 'File selected',
  step2_sponsor_title: 'Sponsor Materials (Optional)',
  step2_sponsor_filled: '[Filled]',
  step2_sponsor_remaining: 'remaining',
  step2_family_title: 'Family Members (Optional)',
  step2_family_add: '+ Add Family Member',
  step2_family_remove: 'Remove',
  step2_family_name: 'Name',
  step2_total_base: 'Base Fee',
  step2_total_sponsor: 'Sponsorship Total',
  step2_total_grand: 'Grand Total',
  step3_pending_title: 'Registration Submitted!',
  step3_pending_body: 'Your registration has been received and is pending admin verification. Once approved, a WhatsApp communication link will be unlocked below.',
  step3_approved_title: 'Registration Approved!',
  step3_whatsapp_unlocked: 'WhatsApp link is now active. Click below to send your details to the priest.',
  step3_whatsapp_btn: 'Send Details to Priest via WhatsApp',
  step3_edit: 'Edit Submission',
  step3_submit_another: 'Submit Another Registration',
  event_no_events: 'No active events at this time. Please check back later.',
  carousel_loading: 'Loading events...',
  form_loading: 'Submitting...',
  form_success: 'Registration submitted successfully!',
  form_error: 'An error occurred. Please try again.',
  form_required: 'This field is required',
  invalid_whatsapp: 'Invalid WhatsApp number format',
  invalid_email: 'Invalid email address',
  approval_pending: 'Pending',
  approval_approved: 'Approved',
  approval_rejected: 'Rejected',
  settings_title: 'Account Settings',
  settings_email_label: 'Update Email',
  settings_password_label: 'Change Password',
  settings_new_email: 'New Email',
  settings_new_password: 'New Password',
  settings_confirm_password: 'Confirm New Password',
  settings_current_password: 'Current Password',
  settings_save: 'Save Changes',
  settings_success: 'Settings updated successfully.',
  settings_password_mismatch: 'Passwords do not match.',
  admin_management_title: 'Admin Management',
  admin_management_approve: 'Approve',
  admin_management_revoke: 'Revoke',
  admin_management_no_admins: 'No other admins registered.',
  footer_contact: 'Contact Priest: Gurukal Kumarah',
  footer_rights: 'All rights reserved.',
  back_to_public: 'Back to Public View',
  // Feature #1 — devotee status lookup
  status_lookup_title: 'Check Registration Status',
  status_lookup_subtitle: 'Enter your reference ID or WhatsApp number to see if your pooja is confirmed.',
  status_lookup_open: 'Check My Status',
  status_lookup_ref_label: 'Reference ID',
  status_lookup_ref_placeholder: 'Paste your reference ID',
  status_lookup_wa_label: 'WhatsApp Number',
  status_lookup_wa_placeholder: 'e.g. 0123456789',
  status_lookup_or: 'or',
  status_lookup_submit: 'Check Status',
  status_lookup_checking: 'Checking…',
  status_lookup_none: 'No registration found. Please check your reference ID or WhatsApp number.',
  status_lookup_empty_input: 'Enter a reference ID or WhatsApp number.',
  status_lookup_error: 'Something went wrong. Please try again.',
  status_lookup_result_title: 'Your Registration',
  status_lookup_event: 'Event',
  status_lookup_submitted: 'Submitted',
  status_lookup_close: 'Close',
  // Feature #2 — material sponsorship progress
  material_needed_title: 'Materials Needed',
  material_sponsored_suffix: 'sponsored',
  material_filled: 'Filled',
  material_more: 'more',
  // Feature #3 — receipt thumbnail + lightbox
  receipt_view: 'Receipt',
  receipt_tap_enlarge: 'Tap to enlarge',
  receipt_unavailable: 'Receipt unavailable',
  receipt_open_new: 'Open in new tab',
  receipt_close: 'Close',
  // Feature #4 — per-event financial rollup
  rollup_title: 'Per-Event Breakdown',
  rollup_show: 'Show breakdown',
  rollup_hide: 'Hide breakdown',
  rollup_registrations: 'Registrations',
  rollup_collected: 'Collected',
  rollup_awaiting: 'Awaiting',
  rollup_empty: 'No event data yet.',
  // Feature #5 — approval audit trail
  audit_actioned_by: 'Actioned by',
  // Feature #6 — PWA install
  pwa_install: 'Install App',
  pwa_install_hint: 'Add this bulletin to your home screen',
  pwa_install_dismiss: 'Not now',
};

const TA: TranslationDict = {
  app_title: 'கோயில் நிதி & பக்தர் அறிக்கை',
  lang_en: 'EN',
  lang_ta: 'தமிழ்',
  lang_bm: 'BM',
  contribute_now: 'இப்பொழுதே பங்களிக்கவும்',
  admin_dashboard: 'நிர்வாக முகப்பு',
  admin_login: 'நிர்வாக உள்நுழைவு',
  admin_logout: 'வெளியேறு',
  admin_tab_login: 'உள்நுழைவு',
  admin_tab_register: 'பதிவு செய்',
  admin_email_placeholder: 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
  admin_password_placeholder: 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
  admin_confirm_password_placeholder: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
  admin_invalid_credentials: 'உள்நுழைவு தோல்வி. உங்கள் சான்றுகளை சரிபார்க்கவும்.',
  admin_forgot_password: 'கடவுச்சொல் மறந்துவிட்டதா?',
  admin_show_password: 'காட்டு',
  admin_hide_password: 'மறை',
  admin_register_success_message: 'கணக்கு உருவாக்கப்பட்டது. உறுதிப்படுத்த உங்கள் மின்னஞ்சலைச் சரிபார்க்கவும், பின்னர் தற்போதைய நிர்வாகி உங்கள் அணுகலை அனுமதிக்க வேண்டும்.',
  auth_forgot_success: 'கணக்கு இருந்தால், கடவுச்சொல் மீட்டமைப்பு இணைப்பு அனுப்பப்பட்டுள்ளது.',
  auth_user_not_found: 'இந்த மின்னஞ்சலுடன் கணக்கு எதுவும் இல்லை.',
  auth_invalid_credentials: 'தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்.',
  auth_email_not_confirmed: 'முதலில் உங்கள் மின்னஞ்சல் முகவரியை உறுதிப்படுத்தவும்.',
  auth_not_approved: 'உங்கள் நிர்வாக கணக்கு இன்னும் அனுமதிக்கப்படவில்லை.',
  admin_pending_approval_title: 'நிர்வாக அனுமதி நிலுவையில்',
  admin_pending_approval_body: 'உங்கள் நிர்வாக கணக்கு உருவாக்கப்பட்டது ஆனால் தற்போதைய நிர்வாகியின் அனுமதி தேவை. அனுமதிக்கப்படும் வரை காத்திருக்கவும்.',
  admin_submissions_title: 'பக்தர் பதிவுகள்',
  admin_event: 'நிகழ்வு',
  admin_name: 'பெயர்',
  admin_whatsapp: 'வாட்ஸ்அப்',
  admin_email: 'மின்னஞ்சல்',
  admin_amount: 'தொகை (RM)',
  admin_proof: 'ரசீது',
  admin_status: 'நிலை',
  admin_actions: 'செயல்கள்',
  admin_approve: 'அனுமதி',
  admin_reject: 'நிராகரி',
  admin_whatsapp_btn: 'வாட்ஸ்அப் அனுப்பு',
  admin_no_submissions: 'இதுவரை பதிவுகள் இல்லை.',
  admin_table_loading: 'பதிவுகள் ஏற்றப்படுகின்றன...',
  admin_no_submissions_hint: 'சமர்ப்பிக்கப்பட்டவுடன் பக்தர்களின் பதிவுகள் இங்கே தோன்றும்.',
  admin_refresh: 'புதுப்பி',
  admin_export_csv: 'CSV ஏற்றுமதி',
  admin_search_placeholder: 'பெயர், வாட்ஸ்அப் அல்லது மின்னஞ்சல் தேடு…',
  admin_filter_all: 'அனைத்தும்',
  admin_no_results: 'உங்கள் தேடலுக்கு பொருந்தும் பதிவுகள் இல்லை.',
  admin_stat_total: 'மொத்தம்',
  admin_stat_pending: 'நிலுவையில்',
  admin_stat_approved: 'அங்கீகரிக்கப்பட்டது',
  admin_stat_rejected: 'நிராகரிக்கப்பட்டது',
  admin_stat_collected: 'வசூலிக்கப்பட்டது',
  admin_stat_awaiting: 'எதிர்பார்ப்பு',
  admin_events_title: 'நிகழ்வுகள்',
  admin_natchatram: 'நட்சத்திரம்',
  admin_rasi: 'ராசி',
  admin_family: 'குடும்ப உறுப்பினர்கள்',
  admin_materials: 'நன்கொடை பொருட்கள்',
  admin_submitted_at: 'சமர்ப்பிக்கப்பட்டது',
  admin_ref: 'குறிப்பு',
  admin_view_details: 'விவரங்கள்',
  admin_hide_details: 'மறை',
  admin_mark_pending: 'நிலுவையாக குறி',
  admin_copy_wa: 'வாட்ஸ்அப் நகலெடு',
  admin_copied: 'நகலெடுக்கப்பட்டது!',
  admin_none_provided: '—',
  events_admin_title: 'நிகழ்வுகளை நிர்வகி',
  events_admin_new: 'புதிய நிகழ்வு',
  events_admin_edit: 'திருத்து',
  events_admin_delete: 'நீக்கு',
  events_admin_delete_confirm: 'இந்த நிகழ்வை நீக்கவா? இதை மீட்டமைக்க முடியாது.',
  events_admin_name: 'நிகழ்வின் பெயர்',
  events_admin_cost: 'ஒருவருக்கான கட்டணம் (RM)',
  events_admin_time: 'அபிஷேக நேரம்',
  events_admin_notes: 'சிறப்பு குறிப்புகள்',
  events_admin_poster: 'சுவரொட்டி படத்தின் URL',
  events_admin_status: 'நிலை',
  events_admin_carousel: 'சுழற்சியில் காட்டு',
  events_admin_save: 'நிகழ்வைச் சேமி',
  events_admin_cancel: 'ரத்து செய்',
  events_admin_saved: 'நிகழ்வு சேமிக்கப்பட்டது.',
  events_admin_deleted: 'நிகழ்வு நீக்கப்பட்டது.',
  events_admin_error: 'நிகழ்வைச் சேமிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  events_admin_none: 'இன்னும் நிகழ்வுகள் இல்லை. தொடங்க ஒன்றை உருவாக்கவும்.',
  events_admin_required: 'நிகழ்வின் பெயர் தேவை.',
  step1_title: 'படி 1: கட்டண விவரங்கள்',
  step2_title: 'படி 2: பதிவு',
  step3_title: 'படி 3: உறுதிப்படுத்தல்',
  step_short_1: 'கட்டணம்',
  step_short_2: 'பதிவு',
  step_short_3: 'முடிவு',
  contribute_close: 'படிவத்தை மூடு',
  contact_name: 'முழு பெயர்',
  contact_name_placeholder: 'உங்கள் முழு பெயரை உள்ளிடவும்',
  contact_whatsapp: 'வாட்ஸ்அப் எண்',
  contact_whatsapp_placeholder: 'எ.கா. 0123456789',
  contact_email: 'மின்னஞ்சல்',
  contact_email_placeholder: 'you@example.com',
  contact_natchatram: 'நட்சத்திரம்',
  contact_rasi: 'ராசி',
  step1_bank_label: 'வங்கி',
  step1_account_label: 'கணக்கு பெயர்',
  step1_number_label: 'கணக்கு எண்',
  step1_cost_label: 'ஒரு நபருக்கான செலவு',
  step1_scan_qr: 'கட்டணம் செலுத்த QR குறியீட்டை ஸ்கேன் செய்யவும்',
  step2_next: 'பதிவுக்கு செல்லவும்',
  step2_submit: 'பதிவை சமர்ப்பிக்கவும்',
  step2_upload_receipt: 'கட்டண ரசீதை பதிவேற்றவும்',
  step2_drag_drop: 'இழுத்து விடவும் அல்லது கிளிக் செய்து பதிவேற்றவும்',
  step2_file_selected: 'கோப்பு தேர்ந்தெடுக்கப்பட்டது',
  step2_sponsor_title: 'பொருட்களை நிதியளிக்கவும் (விருப்பத்தேர்வு)',
  step2_sponsor_filled: '[நிரம்பியது]',
  step2_sponsor_remaining: 'மீதமுள்ளது',
  step2_family_title: 'குடும்ப உறுப்பினர்கள் (விருப்பத்தேர்வு)',
  step2_family_add: '+ குடும்ப உறுப்பினரைச் சேர்',
  step2_family_remove: 'நீக்கு',
  step2_family_name: 'பெயர்',
  step2_total_base: 'அடிப்படை கட்டணம்',
  step2_total_sponsor: 'நிதியுதவி மொத்தம்',
  step2_total_grand: 'மொத்த தொகை',
  step3_pending_title: 'பதிவு சமர்ப்பிக்கப்பட்டது!',
  step3_pending_body: 'உங்கள் பதிவு பெறப்பட்டு நிர்வாக சரிபார்ப்புக்காக காத்திருக்கிறது. அனுமதிக்கப்பட்டவுடன், வாட்ஸ்அப் தொடர்பு இணைப்பு கீழே திறக்கப்படும்.',
  step3_approved_title: 'பதிவு அனுமதிக்கப்பட்டது!',
  step3_whatsapp_unlocked: 'வாட்ஸ்அப் இணைப்பு செயலில் உள்ளது. உங்கள் விவரங்களை பூசாரிக்கு அனுப்ப கீழே கிளிக் செய்யவும்.',
  step3_whatsapp_btn: 'வாட்ஸ்அப் மூலம் பூசாரிக்கு விவரங்களை அனுப்பவும்',
  step3_edit: 'சமர்ப்பிப்பைத் திருத்து',
  step3_submit_another: 'மற்றொரு பதிவைச் சமர்ப்பிக்கவும்',
  event_no_events: 'தற்போது செயலில் நிகழ்வுகள் இல்லை. பின்னர் சரிபார்க்கவும்.',
  carousel_loading: 'நிகழ்வுகள் ஏற்றப்படுகின்றன...',
  form_loading: 'சமர்ப்பிக்கிறது...',
  form_success: 'பதிவு வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!',
  form_error: 'பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.',
  form_required: 'இந்த புலம் தேவை',
  invalid_whatsapp: 'தவறான வாட்ஸ்அப் எண் வடிவம்',
  invalid_email: 'தவறான மின்னஞ்சல் முகவரி',
  approval_pending: 'நிலுவையில்',
  approval_approved: 'அனுமதிக்கப்பட்டது',
  approval_rejected: 'நிராகரிக்கப்பட்டது',
  settings_title: 'கணக்கு அமைப்புகள்',
  settings_email_label: 'மின்னஞ்சலைப் புதுப்பி',
  settings_password_label: 'கடவுச்சொல்லை மாற்று',
  settings_new_email: 'புதிய மின்னஞ்சல்',
  settings_new_password: 'புதிய கடவுச்சொல்',
  settings_confirm_password: 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
  settings_current_password: 'தற்போதைய கடவுச்சொல்',
  settings_save: 'மாற்றங்களைச் சேமி',
  settings_success: 'அமைப்புகள் வெற்றிகரமாக புதுப்பிக்கப்பட்டன.',
  settings_password_mismatch: 'கடவுச்சொற்கள் பொருந்தவில்லை.',
  admin_management_title: 'நிர்வாக மேலாண்மை',
  admin_management_approve: 'அனுமதி',
  admin_management_revoke: 'ரத்து செய்',
  admin_management_no_admins: 'வேறு நிர்வாகிகள் பதிவு செய்யப்படவில்லை.',
  footer_contact: 'பூசாரியை தொடர்பு கொள்ள: குருக்கள் குமாரா',
  footer_rights: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
  back_to_public: 'பொது பார்வைக்கு திரும்பு',
  // Feature #1 — devotee status lookup
  status_lookup_title: 'பதிவு நிலையைச் சரிபார்க்கவும்',
  status_lookup_subtitle: 'உங்கள் பூஜை உறுதிசெய்யப்பட்டதா என அறிய உங்கள் குறிப்பு ஐடி அல்லது வாட்ஸ்அப் எண்ணை உள்ளிடவும்.',
  status_lookup_open: 'எனது நிலையைச் சரிபார்',
  status_lookup_ref_label: 'குறிப்பு ஐடி',
  status_lookup_ref_placeholder: 'உங்கள் குறிப்பு ஐடியை ஒட்டவும்',
  status_lookup_wa_label: 'வாட்ஸ்அப் எண்',
  status_lookup_wa_placeholder: 'எ.கா. 0123456789',
  status_lookup_or: 'அல்லது',
  status_lookup_submit: 'நிலையைச் சரிபார்',
  status_lookup_checking: 'சரிபார்க்கிறது…',
  status_lookup_none: 'பதிவு எதுவும் கிடைக்கவில்லை. உங்கள் குறிப்பு ஐடி அல்லது வாட்ஸ்அப் எண்ணைச் சரிபார்க்கவும்.',
  status_lookup_empty_input: 'குறிப்பு ஐடி அல்லது வாட்ஸ்அப் எண்ணை உள்ளிடவும்.',
  status_lookup_error: 'ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.',
  status_lookup_result_title: 'உங்கள் பதிவு',
  status_lookup_event: 'நிகழ்வு',
  status_lookup_submitted: 'சமர்ப்பிக்கப்பட்டது',
  status_lookup_close: 'மூடு',
  // Feature #2 — material sponsorship progress
  material_needed_title: 'தேவையான பொருட்கள்',
  material_sponsored_suffix: 'நன்கொடை அளிக்கப்பட்டது',
  material_filled: 'நிரம்பியது',
  material_more: 'மேலும்',
  // Feature #3 — receipt thumbnail + lightbox
  receipt_view: 'ரசீது',
  receipt_tap_enlarge: 'பெரிதாக்க தட்டவும்',
  receipt_unavailable: 'ரசீது கிடைக்கவில்லை',
  receipt_open_new: 'புதிய தாவலில் திற',
  receipt_close: 'மூடு',
  // Feature #4 — per-event financial rollup
  rollup_title: 'நிகழ்வு வாரியான விவரம்',
  rollup_show: 'விவரத்தைக் காட்டு',
  rollup_hide: 'விவரத்தை மறை',
  rollup_registrations: 'பதிவுகள்',
  rollup_collected: 'வசூலிக்கப்பட்டது',
  rollup_awaiting: 'எதிர்பார்ப்பு',
  rollup_empty: 'இன்னும் நிகழ்வு தரவு இல்லை.',
  // Feature #5 — approval audit trail
  audit_actioned_by: 'செயல்படுத்தியவர்',
  // Feature #6 — PWA install
  pwa_install: 'செயலியை நிறுவு',
  pwa_install_hint: 'இந்த அறிக்கையை முகப்புத் திரையில் சேர்க்கவும்',
  pwa_install_dismiss: 'இப்போது வேண்டாம்',
};

const BM: TranslationDict = {
  app_title: 'Dana Kuil & Buletin Penganut',
  lang_en: 'EN',
  lang_ta: 'தமிழ்',
  lang_bm: 'BM',
  contribute_now: 'Menyumbang Sekarang',
  admin_dashboard: 'Papan Pemuka Admin',
  admin_login: 'Log Masuk Admin',
  admin_logout: 'Log Keluar',
  admin_tab_login: 'Log Masuk',
  admin_tab_register: 'Daftar',
  admin_email_placeholder: 'Masukkan emel anda',
  admin_password_placeholder: 'Masukkan kata laluan anda',
  admin_confirm_password_placeholder: 'Sahkan kata laluan anda',
  admin_invalid_credentials: 'Log masuk gagal. Sila periksa bukti kelayakan anda.',
  admin_forgot_password: 'Lupa Kata Laluan?',
  admin_show_password: 'Tunjuk',
  admin_hide_password: 'Sembunyi',
  admin_register_success_message: 'Akaun dibuat. Semak emel untuk pengesahan, kemudian admin sedia ada mesti meluluskan akses anda.',
  auth_forgot_success: 'Jika akaun wujud, pautan tetapan semula kata laluan telah dihantar.',
  auth_user_not_found: 'Tiada akaun ditemui dengan emel ini.',
  auth_invalid_credentials: 'Emel atau kata laluan tidak sah.',
  auth_email_not_confirmed: 'Sila sahkan alamat emel anda terlebih dahulu.',
  auth_not_approved: 'Akaun admin anda belum diluluskan.',
  admin_pending_approval_title: 'Menunggu Kelulusan Admin',
  admin_pending_approval_body: 'Akaun admin anda telah dibuat tetapi memerlukan kelulusan daripada pentadbir sedia ada. Sila tunggu untuk diluluskan.',
  admin_submissions_title: 'Pendaftaran Penganut',
  admin_event: 'Acara',
  admin_name: 'Nama',
  admin_whatsapp: 'WhatsApp',
  admin_email: 'Emel',
  admin_amount: 'Jumlah (RM)',
  admin_proof: 'Resit',
  admin_status: 'Status',
  admin_actions: 'Tindakan',
  admin_approve: 'Luluskan',
  admin_reject: 'Tolak',
  admin_whatsapp_btn: 'Hantar WhatsApp',
  admin_no_submissions: 'Tiada pendaftaran lagi.',
  admin_table_loading: 'Memuat pendaftaran...',
  admin_no_submissions_hint: 'Pendaftaran daripada penganut akan muncul di sini setelah dihantar.',
  admin_refresh: 'Muat Semula',
  admin_export_csv: 'Eksport CSV',
  admin_search_placeholder: 'Cari nama, WhatsApp atau e-mel…',
  admin_filter_all: 'Semua',
  admin_no_results: 'Tiada pendaftaran sepadan dengan carian anda.',
  admin_stat_total: 'Jumlah',
  admin_stat_pending: 'Menunggu',
  admin_stat_approved: 'Diluluskan',
  admin_stat_rejected: 'Ditolak',
  admin_stat_collected: 'Dikutip',
  admin_stat_awaiting: 'Menanti',
  admin_events_title: 'Acara',
  admin_natchatram: 'Natchatram',
  admin_rasi: 'Rasi',
  admin_family: 'Ahli Keluarga',
  admin_materials: 'Bahan Ditaja',
  admin_submitted_at: 'Dihantar',
  admin_ref: 'Ruj',
  admin_view_details: 'Butiran',
  admin_hide_details: 'Sembunyi',
  admin_mark_pending: 'Tanda Menunggu',
  admin_copy_wa: 'Salin WhatsApp',
  admin_copied: 'Disalin!',
  admin_none_provided: '—',
  events_admin_title: 'Urus Acara',
  events_admin_new: 'Acara Baharu',
  events_admin_edit: 'Sunting',
  events_admin_delete: 'Padam',
  events_admin_delete_confirm: 'Padam acara ini? Tindakan ini tidak boleh dibatalkan.',
  events_admin_name: 'Nama Acara',
  events_admin_cost: 'Kos setiap orang (RM)',
  events_admin_time: 'Masa Abhishegam',
  events_admin_notes: 'Nota Khas',
  events_admin_poster: 'URL Imej Poster',
  events_admin_status: 'Status',
  events_admin_carousel: 'Papar dalam Karusel',
  events_admin_save: 'Simpan Acara',
  events_admin_cancel: 'Batal',
  events_admin_saved: 'Acara disimpan.',
  events_admin_deleted: 'Acara dipadam.',
  events_admin_error: 'Tidak dapat menyimpan acara. Sila cuba lagi.',
  events_admin_none: 'Tiada acara lagi. Cipta satu untuk bermula.',
  events_admin_required: 'Nama acara diperlukan.',
  step1_title: 'Langkah 1: Butiran Bayaran',
  step2_title: 'Langkah 2: Pendaftaran',
  step3_title: 'Langkah 3: Pengesahan',
  step_short_1: 'Bayaran',
  step_short_2: 'Daftar',
  step_short_3: 'Selesai',
  contribute_close: 'Tutup Borang',
  contact_name: 'Nama Penuh',
  contact_name_placeholder: 'Masukkan nama penuh anda',
  contact_whatsapp: 'Nombor WhatsApp',
  contact_whatsapp_placeholder: 'cth. 0123456789',
  contact_email: 'E-mel',
  contact_email_placeholder: 'anda@contoh.com',
  contact_natchatram: 'Natchatram (Bintang Kelahiran)',
  contact_rasi: 'Rasi (Zodiak)',
  step1_bank_label: 'Bank',
  step1_account_label: 'Nama Akaun',
  step1_number_label: 'Nombor Akaun',
  step1_cost_label: 'Kos Seorang',
  step1_scan_qr: 'Imbas Kod QR untuk Membayar',
  step2_next: 'Teruskan ke Pendaftaran',
  step2_submit: 'Hantar Pendaftaran',
  step2_upload_receipt: 'Muat Naik Resit Bayaran',
  step2_drag_drop: 'Seret & lepas atau klik untuk muat naik',
  step2_file_selected: 'Fail dipilih',
  step2_sponsor_title: 'Taja Bahan (Pilihan)',
  step2_sponsor_filled: '[Penuh]',
  step2_sponsor_remaining: 'baki',
  step2_family_title: 'Ahli Keluarga (Pilihan)',
  step2_family_add: '+ Tambah Ahli Keluarga',
  step2_family_remove: 'Buang',
  step2_family_name: 'Nama',
  step2_total_base: 'Yuran Asas',
  step2_total_sponsor: 'Jumlah Tajaan',
  step2_total_grand: 'Jumlah Besar',
  step3_pending_title: 'Pendaftaran Dihantar!',
  step3_pending_body: 'Pendaftaran anda telah diterima dan menunggu pengesahan admin. Setelah diluluskan, pautan WhatsApp akan dibuka di bawah.',
  step3_approved_title: 'Pendaftaran Diluluskan!',
  step3_whatsapp_unlocked: 'Pautan WhatsApp kini aktif. Klik di bawah untuk hantar butiran anda kepada paderi.',
  step3_whatsapp_btn: 'Hantar Butiran kepada Paderi melalui WhatsApp',
  step3_edit: 'Sunting Penyerahan',
  step3_submit_another: 'Hantar Pendaftaran Lain',
  event_no_events: 'Tiada acara aktif buat masa ini. Sila semak semula kemudian.',
  carousel_loading: 'Memuat acara...',
  form_loading: 'Menghantar...',
  form_success: 'Pendaftaran berjaya dihantar!',
  form_error: 'Ralat berlaku. Sila cuba lagi.',
  form_required: 'Ruangan ini diperlukan',
  invalid_whatsapp: 'Format nombor WhatsApp tidak sah',
  invalid_email: 'Alamat emel tidak sah',
  approval_pending: 'Tertunda',
  approval_approved: 'Diluluskan',
  approval_rejected: 'Ditolak',
  settings_title: 'Tetapan Akaun',
  settings_email_label: 'Kemas Kini Emel',
  settings_password_label: 'Tukar Kata Laluan',
  settings_new_email: 'Emel Baru',
  settings_new_password: 'Kata Laluan Baru',
  settings_confirm_password: 'Sahkan Kata Laluan Baru',
  settings_current_password: 'Kata Laluan Semasa',
  settings_save: 'Simpan Perubahan',
  settings_success: 'Tetapan berjaya dikemas kini.',
  settings_password_mismatch: 'Kata laluan tidak sepadan.',
  admin_management_title: 'Pengurusan Admin',
  admin_management_approve: 'Luluskan',
  admin_management_revoke: 'Batalkan',
  admin_management_no_admins: 'Tiada admin lain didaftarkan.',
  footer_contact: 'Hubungi Paderi: Gurukal Kumarah',
  footer_rights: 'Hak cipta terpelihara.',
  back_to_public: 'Kembali ke Paparan Awam',
  // Feature #1 — devotee status lookup
  status_lookup_title: 'Semak Status Pendaftaran',
  status_lookup_subtitle: 'Masukkan ID rujukan atau nombor WhatsApp anda untuk melihat sama ada pooja anda disahkan.',
  status_lookup_open: 'Semak Status Saya',
  status_lookup_ref_label: 'ID Rujukan',
  status_lookup_ref_placeholder: 'Tampal ID rujukan anda',
  status_lookup_wa_label: 'Nombor WhatsApp',
  status_lookup_wa_placeholder: 'cth. 0123456789',
  status_lookup_or: 'atau',
  status_lookup_submit: 'Semak Status',
  status_lookup_checking: 'Menyemak…',
  status_lookup_none: 'Tiada pendaftaran ditemui. Sila semak ID rujukan atau nombor WhatsApp anda.',
  status_lookup_empty_input: 'Masukkan ID rujukan atau nombor WhatsApp.',
  status_lookup_error: 'Sesuatu tidak kena. Sila cuba lagi.',
  status_lookup_result_title: 'Pendaftaran Anda',
  status_lookup_event: 'Acara',
  status_lookup_submitted: 'Dihantar',
  status_lookup_close: 'Tutup',
  // Feature #2 — material sponsorship progress
  material_needed_title: 'Bahan Diperlukan',
  material_sponsored_suffix: 'ditaja',
  material_filled: 'Penuh',
  material_more: 'lagi',
  // Feature #3 — receipt thumbnail + lightbox
  receipt_view: 'Resit',
  receipt_tap_enlarge: 'Ketik untuk besarkan',
  receipt_unavailable: 'Resit tidak tersedia',
  receipt_open_new: 'Buka dalam tab baharu',
  receipt_close: 'Tutup',
  // Feature #4 — per-event financial rollup
  rollup_title: 'Pecahan Setiap Acara',
  rollup_show: 'Tunjuk pecahan',
  rollup_hide: 'Sembunyi pecahan',
  rollup_registrations: 'Pendaftaran',
  rollup_collected: 'Dikutip',
  rollup_awaiting: 'Menanti',
  rollup_empty: 'Tiada data acara lagi.',
  // Feature #5 — approval audit trail
  audit_actioned_by: 'Ditindak oleh',
  // Feature #6 — PWA install
  pwa_install: 'Pasang Apl',
  pwa_install_hint: 'Tambah buletin ini ke skrin utama',
  pwa_install_dismiss: 'Bukan sekarang',
};

const DICTIONARIES: Record<Language, TranslationDict> = { EN, TA, BM };

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  language: 'EN',
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('EN');

  const t = useCallback(
    (key: string): string => {
      const dict = DICTIONARIES[language];
      return dict[key] ?? EN[key] ?? key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextValue {
  return useContext(LanguageContext);
}
