import { createContext, useContext, useState, useCallback, type ReactNode } from 'react';
import type { Language } from '@/types';

type TranslationDict = Record<string, string>;

const EN: TranslationDict = {
  app_title: 'Temple Fund & Devotee Bulletin',
  lang_en: 'EN',
  lang_ta: 'தமிழ்',
  lang_bm: 'BM',
  contribute_now: 'Contribute Now',
  admin_dashboard: 'Admin Dashboard',
  admin_login: 'Admin Login',
  admin_logout: 'Logout',
  admin_tab_login: 'Login',
  admin_tab_register: 'Register',
  admin_email_placeholder: 'Enter your email',
  admin_password_placeholder: 'Enter your password',
  admin_confirm_password_placeholder: 'Confirm your password',
  admin_invalid_credentials: 'Sign in failed. Please check your credentials.',
  admin_forgot_password: 'Forgot Password?',
  admin_show_password: 'Show',
  admin_hide_password: 'Hide',
  admin_register_success_message: 'Account created. Check your email for confirmation, then an existing admin must approve your access.',
  auth_forgot_success: 'If an account exists, a password reset link has been sent.',
  auth_user_not_found: 'No account found with this email.',
  auth_invalid_credentials: 'Invalid email or password.',
  auth_email_not_confirmed: 'Please confirm your email address first.',
  auth_not_approved: 'Your admin account has not been approved yet.',
  admin_pending_approval_title: 'Pending Admin Approval',
  admin_pending_approval_body: 'Your admin account has been created but requires approval from an existing administrator. Please wait to be approved.',
  admin_submissions_title: 'Devotee Submissions',
  admin_event: 'Event',
  admin_name: 'Name',
  admin_whatsapp: 'WhatsApp',
  admin_email: 'Email',
  admin_amount: 'Amount (RM)',
  admin_proof: 'Receipt',
  admin_status: 'Status',
  admin_actions: 'Actions',
  admin_approve: 'Approve',
  admin_reject: 'Reject',
  admin_whatsapp_btn: 'Send WhatsApp',
  admin_no_submissions: 'No submissions yet.',
  admin_table_loading: 'Loading submissions...',
  step1_title: 'Step 1: Payment Details',
  step2_title: 'Step 2: Registration',
  step3_title: 'Step 3: Confirmation',
  step_short_1: 'Payment',
  step_short_2: 'Register',
  step_short_3: 'Done',
  contribute_close: 'Close Form',
  contact_name: 'Full Name',
  contact_name_placeholder: 'Enter your full name',
  contact_whatsapp: 'WhatsApp Number',
  contact_whatsapp_placeholder: 'e.g. 0123456789',
  contact_email: 'Email',
  contact_email_placeholder: 'you@example.com',
  contact_natchatram: 'Natchatram (Birth Star)',
  contact_rasi: 'Rasi (Zodiac)',
  step1_bank_label: 'Bank',
  step1_account_label: 'Account Name',
  step1_number_label: 'Account Number',
  step1_cost_label: 'Cost Per Person',
  step1_scan_qr: 'Scan QR Code to Pay',
  step2_next: 'Proceed to Registration',
  step2_submit: 'Submit Registration',
  step2_upload_receipt: 'Upload Payment Receipt',
  step2_drag_drop: 'Drag & drop or click to upload',
  step2_file_selected: 'File selected',
  step2_sponsor_title: 'Sponsor Materials (Optional)',
  step2_sponsor_filled: '[Filled]',
  step2_sponsor_remaining: 'remaining',
  step2_family_title: 'Family Members (Optional)',
  step2_family_add: '+ Add Family Member',
  step2_family_remove: 'Remove',
  step2_family_name: 'Name',
  step2_total_base: 'Base Fee',
  step2_total_sponsor: 'Sponsorship Total',
  step2_total_grand: 'Grand Total',
  step3_pending_title: 'Registration Submitted!',
  step3_pending_body: 'Your registration has been received and is pending admin verification. Once approved, a WhatsApp communication link will be unlocked below.',
  step3_approved_title: 'Registration Approved!',
  step3_whatsapp_unlocked: 'WhatsApp link is now active. Click below to send your details to the priest.',
  step3_whatsapp_btn: 'Send Details to Priest via WhatsApp',
  event_no_events: 'No active events at this time. Please check back later.',
  carousel_loading: 'Loading events...',
  form_loading: 'Submitting...',
  form_success: 'Registration submitted successfully!',
  form_error: 'An error occurred. Please try again.',
  form_required: 'This field is required',
  invalid_whatsapp: 'Invalid WhatsApp number format',
  invalid_email: 'Invalid email address',
  approval_pending: 'Pending',
  approval_approved: 'Approved',
  approval_rejected: 'Rejected',
  settings_title: 'Account Settings',
  settings_email_label: 'Update Email',
  settings_password_label: 'Change Password',
  settings_new_email: 'New Email',
  settings_new_password: 'New Password',
  settings_confirm_password: 'Confirm New Password',
  settings_current_password: 'Current Password',
  settings_save: 'Save Changes',
  settings_success: 'Settings updated successfully.',
  settings_password_mismatch: 'Passwords do not match.',
  admin_management_title: 'Admin Management',
  admin_management_approve: 'Approve',
  admin_management_revoke: 'Revoke',
  admin_management_no_admins: 'No other admins registered.',
  footer_contact: 'Contact Priest: Gurukal Kumarah',
  footer_rights: 'All rights reserved.',
  back_to_public: 'Back to Public View',
};

const TA: TranslationDict = {
  app_title: 'கோயில் நிதி & பக்தர் அறிக்கை',
  lang_en: 'EN',
  lang_ta: 'தமிழ்',
  lang_bm: 'BM',
  contribute_now: 'இப்பொழுதே பங்களிக்கவும்',
  admin_dashboard: 'நிர்வாக முகப்பு',
  admin_login: 'நிர்வாக உள்நுழைவு',
  admin_logout: 'வெளியேறு',
  admin_tab_login: 'உள்நுழைவு',
  admin_tab_register: 'பதிவு செய்',
  admin_email_placeholder: 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
  admin_password_placeholder: 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
  admin_confirm_password_placeholder: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
  admin_invalid_credentials: 'உள்நுழைவு தோல்வி. உங்கள் சான்றுகளை சரிபார்க்கவும்.',
  admin_forgot_password: 'கடவுச்சொல் மறந்துவிட்டதா?',
  admin_show_password: 'காட்டு',
  admin_hide_password: 'மறை',
  admin_register_success_message: 'கணக்கு உருவாக்கப்பட்டது. உறுதிப்படுத்த உங்கள் மின்னஞ்சலைச் சரிபார்க்கவும், பின்னர் தற்போதைய நிர்வாகி உங்கள் அணுகலை அனுமதிக்க வேண்டும்.',
  auth_forgot_success: 'கணக்கு இருந்தால், கடவுச்சொல் மீட்டமைப்பு இணைப்பு அனுப்பப்பட்டுள்ளது.',
  auth_user_not_found: 'இந்த மின்னஞ்சலுடன் கணக்கு எதுவும் இல்லை.',
  auth_invalid_credentials: 'தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்.',
  auth_email_not_confirmed: 'முதலில் உங்கள் மின்னஞ்சல் முகவரியை உறுதிப்படுத்தவும்.',
  auth_not_approved: 'உங்கள் நிர்வாக கணக்கு இன்னும் அனுமதிக்கப்படவில்லை.',
  admin_pending_approval_title: 'நிர்வாக அனுமதி நிலுவையில்',
  admin_pending_approval_body: 'உங்கள் நிர்வாக கணக்கு உருவாக்கப்பட்டது ஆனால் தற்போதைய நிர்வாகியின் அனுமதி தேவை. அனுமதிக்கப்படும் வரை காத்திருக்கவும்.',
  admin_submissions_title: 'பக்தர் பதிவுகள்',
  admin_event: 'நிகழ்வு',
  admin_name: 'பெயர்',
  admin_whatsapp: 'வாட்ஸ்அப்',
  admin_email: 'மின்னஞ்சல்',
  admin_amount: 'தொகை (RM)',
  admin_proof: 'ரசீது',
  admin_status: 'நிலை',
  admin_actions: 'செயல்கள்',
  admin_approve: 'அனுமதி',
  admin_reject: 'நிராகரி',
  admin_whatsapp_btn: 'வாட்ஸ்அப் அனுப்பு',
  admin_no_submissions: 'இதுவரை பதிவுகள் இல்லை.',
  admin_table_loading: 'பதிவுகள் ஏற்றப்படுகின்றன...',
  step1_title: 'படி 1: கட்டண விவரங்கள்',
  step2_title: 'படி 2: பதிவு',
  step3_title: 'படி 3: உறுதிப்படுத்தல்',
  step_short_1: 'கட்டணம்',
  step_short_2: 'பதிவு',
  step_short_3: 'முடிவு',
  contribute_close: 'படிவத்தை மூடு',
  contact_name: 'முழு பெயர்',
  contact_name_placeholder: 'உங்கள் முழு பெயரை உள்ளிடவும்',
  contact_whatsapp: 'வாட்ஸ்அப் எண்',
  contact_whatsapp_placeholder: 'எ.கா. 0123456789',
  contact_email: 'மின்னஞ்சல்',
  contact_email_placeholder: 'you@example.com',
  contact_natchatram: 'நட்சத்திரம்',
  contact_rasi: 'ராசி',
  step1_bank_label: 'வங்கி',
  step1_account_label: 'கணக்கு பெயர்',
  step1_number_label: 'கணக்கு எண்',
  step1_cost_label: 'ஒரு நபருக்கான செலவு',
  step1_scan_qr: 'கட்டணம் செலுத்த QR குறியீட்டை ஸ்கேன் செய்யவும்',
  step2_next: 'பதிவுக்கு செல்லவும்',
  step2_submit: 'பதிவை சமர்ப்பிக்கவும்',
  step2_upload_receipt: 'கட்டண ரசீதை பதிவேற்றவும்',
  step2_drag_drop: 'இழுத்து விடவும் அல்லது கிளிக் செய்து பதிவேற்றவும்',
  step2_file_selected: 'கோப்பு தேர்ந்தெடுக்கப்பட்டது',
  step2_sponsor_title: 'பொருட்களை நிதியளிக்கவும் (விருப்பத்தேர்வு)',
  step2_sponsor_filled: '[நிரம்பியது]',
  step2_sponsor_remaining: 'மீதமுள்ளது',
  step2_family_title: 'குடும்ப உறுப்பினர்கள் (விருப்பத்தேர்வு)',
  step2_family_add: '+ குடும்ப உறுப்பினரைச் சேர்',
  step2_family_remove: 'நீக்கு',
  step2_family_name: 'பெயர்',
  step2_total_base: 'அடிப்படை கட்டணம்',
  step2_total_sponsor: 'நிதியுதவி மொத்தம்',
  step2_total_grand: 'மொத்த தொகை',
  step3_pending_title: 'பதிவு சமர்ப்பிக்கப்பட்டது!',
  step3_pending_body: 'உங்கள் பதிவு பெறப்பட்டு நிர்வாக சரிபார்ப்புக்காக காத்திருக்கிறது. அனுமதிக்கப்பட்டவுடன், வாட்ஸ்அப் தொடர்பு இணைப்பு கீழே திறக்கப்படும்.',
  step3_approved_title: 'பதிவு அனுமதிக்கப்பட்டது!',
  step3_whatsapp_unlocked: 'வாட்ஸ்அப் இணைப்பு செயலில் உள்ளது. உங்கள் விவரங்களை பூசாரிக்கு அனுப்ப கீழே கிளிக் செய்யவும்.',
  step3_whatsapp_btn: 'வாட்ஸ்அப் மூலம் பூசாரிக்கு விவரங்களை அனுப்பவும்',
  event_no_events: 'தற்போது செயலில் நிகழ்வுகள் இல்லை. பின்னர் சரிபார்க்கவும்.',
  carousel_loading: 'நிகழ்வுகள் ஏற்றப்படுகின்றன...',
  form_loading: 'சமர்ப்பிக்கிறது...',
  form_success: 'பதிவு வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!',
  form_error: 'பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.',
  form_required: 'இந்த புலம் தேவை',
  invalid_whatsapp: 'தவறான வாட்ஸ்அப் எண் வடிவம்',
  invalid_email: 'தவறான மின்னஞ்சல் முகவரி',
  approval_pending: 'நிலுவையில்',
  approval_approved: 'அனுமதிக்கப்பட்டது',
  approval_rejected: 'நிராகரிக்கப்பட்டது',
  settings_title: 'கணக்கு அமைப்புகள்',
  settings_email_label: 'மின்னஞ்சலைப் புதுப்பி',
  settings_password_label: 'கடவுச்சொல்லை மாற்று',
  settings_new_email: 'புதிய மின்னஞ்சல்',
  settings_new_password: 'புதிய கடவுச்சொல்',
  settings_confirm_password: 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
  settings_current_password: 'தற்போதைய கடவுச்சொல்',
  settings_save: 'மாற்றங்களைச் சேமி',
  settings_success: 'அமைப்புகள் வெற்றிகரமாக புதுப்பிக்கப்பட்டன.',
  settings_password_mismatch: 'கடவுச்சொற்கள் பொருந்தவில்லை.',
  admin_management_title: 'நிர்வாக மேலாண்மை',
  admin_management_approve: 'அனுமதி',
  admin_management_revoke: 'ரத்து செய்',
  admin_management_no_admins: 'வேறு நிர்வாகிகள் பதிவு செய்யப்படவில்லை.',
  footer_contact: 'பூசாரியை தொடர்பு கொள்ள: குருக்கள் குமாரா',
  footer_rights: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
  back_to_public: 'பொது பார்வைக்கு திரும்பு',
};

const BM: TranslationDict = {
  app_title: 'Dana Kuil & Buletin Penganut',
  lang_en: 'EN',
  lang_ta: 'தமிழ்',
  lang_bm: 'BM',
  contribute_now: 'Menyumbang Sekarang',
  admin_dashboard: 'Papan Pemuka Admin',
  admin_login: 'Log Masuk Admin',
  admin_logout: 'Log Keluar',
  admin_tab_login: 'Log Masuk',
  admin_tab_register: 'Daftar',
  admin_email_placeholder: 'Masukkan emel anda',
  admin_password_placeholder: 'Masukkan kata laluan anda',
  admin_confirm_password_placeholder: 'Sahkan kata laluan anda',
  admin_invalid_credentials: 'Log masuk gagal. Sila periksa bukti kelayakan anda.',
  admin_forgot_password: 'Lupa Kata Laluan?',
  admin_show_password: 'Tunjuk',
  admin_hide_password: 'Sembunyi',
  admin_register_success_message: 'Akaun dibuat. Semak emel untuk pengesahan, kemudian admin sedia ada mesti meluluskan akses anda.',
  auth_forgot_success: 'Jika akaun wujud, pautan tetapan semula kata laluan telah dihantar.',
  auth_user_not_found: 'Tiada akaun ditemui dengan emel ini.',
  auth_invalid_credentials: 'Emel atau kata laluan tidak sah.',
  auth_email_not_confirmed: 'Sila sahkan alamat emel anda terlebih dahulu.',
  auth_not_approved: 'Akaun admin anda belum diluluskan.',
  admin_pending_approval_title: 'Menunggu Kelulusan Admin',
  admin_pending_approval_body: 'Akaun admin anda telah dibuat tetapi memerlukan kelulusan daripada pentadbir sedia ada. Sila tunggu untuk diluluskan.',
  admin_submissions_title: 'Pendaftaran Penganut',
  admin_event: 'Acara',
  admin_name: 'Nama',
  admin_whatsapp: 'WhatsApp',
  admin_email: 'Emel',
  admin_amount: 'Jumlah (RM)',
  admin_proof: 'Resit',
  admin_status: 'Status',
  admin_actions: 'Tindakan',
  admin_approve: 'Luluskan',
  admin_reject: 'Tolak',
  admin_whatsapp_btn: 'Hantar WhatsApp',
  admin_no_submissions: 'Tiada pendaftaran lagi.',
  admin_table_loading: 'Memuat pendaftaran...',
  step1_title: 'Langkah 1: Butiran Bayaran',
  step2_title: 'Langkah 2: Pendaftaran',
  step3_title: 'Langkah 3: Pengesahan',
  step_short_1: 'Bayaran',
  step_short_2: 'Daftar',
  step_short_3: 'Selesai',
  contribute_close: 'Tutup Borang',
  contact_name: 'Nama Penuh',
  contact_name_placeholder: 'Masukkan nama penuh anda',
  contact_whatsapp: 'Nombor WhatsApp',
  contact_whatsapp_placeholder: 'cth. 0123456789',
  contact_email: 'E-mel',
  contact_email_placeholder: 'anda@contoh.com',
  contact_natchatram: 'Natchatram (Bintang Kelahiran)',
  contact_rasi: 'Rasi (Zodiak)',
  step1_bank_label: 'Bank',
  step1_account_label: 'Nama Akaun',
  step1_number_label: 'Nombor Akaun',
  step1_cost_label: 'Kos Seorang',
  step1_scan_qr: 'Imbas Kod QR untuk Membayar',
  step2_next: 'Teruskan ke Pendaftaran',
  step2_submit: 'Hantar Pendaftaran',
  step2_upload_receipt: 'Muat Naik Resit Bayaran',
  step2_drag_drop: 'Seret & lepas atau klik untuk muat naik',
  step2_file_selected: 'Fail dipilih',
  step2_sponsor_title: 'Taja Bahan (Pilihan)',
  step2_sponsor_filled: '[Penuh]',
  step2_sponsor_remaining: 'baki',
  step2_family_title: 'Ahli Keluarga (Pilihan)',
  step2_family_add: '+ Tambah Ahli Keluarga',
  step2_family_remove: 'Buang',
  step2_family_name: 'Nama',
  step2_total_base: 'Yuran Asas',
  step2_total_sponsor: 'Jumlah Tajaan',
  step2_total_grand: 'Jumlah Besar',
  step3_pending_title: 'Pendaftaran Dihantar!',
  step3_pending_body: 'Pendaftaran anda telah diterima dan menunggu pengesahan admin. Setelah diluluskan, pautan WhatsApp akan dibuka di bawah.',
  step3_approved_title: 'Pendaftaran Diluluskan!',
  step3_whatsapp_unlocked: 'Pautan WhatsApp kini aktif. Klik di bawah untuk hantar butiran anda kepada paderi.',
  step3_whatsapp_btn: 'Hantar Butiran kepada Paderi melalui WhatsApp',
  event_no_events: 'Tiada acara aktif buat masa ini. Sila semak semula kemudian.',
  carousel_loading: 'Memuat acara...',
  form_loading: 'Menghantar...',
  form_success: 'Pendaftaran berjaya dihantar!',
  form_error: 'Ralat berlaku. Sila cuba lagi.',
  form_required: 'Ruangan ini diperlukan',
  invalid_whatsapp: 'Format nombor WhatsApp tidak sah',
  invalid_email: 'Alamat emel tidak sah',
  approval_pending: 'Tertunda',
  approval_approved: 'Diluluskan',
  approval_rejected: 'Ditolak',
  settings_title: 'Tetapan Akaun',
  settings_email_label: 'Kemas Kini Emel',
  settings_password_label: 'Tukar Kata Laluan',
  settings_new_email: 'Emel Baru',
  settings_new_password: 'Kata Laluan Baru',
  settings_confirm_password: 'Sahkan Kata Laluan Baru',
  settings_current_password: 'Kata Laluan Semasa',
  settings_save: 'Simpan Perubahan',
  settings_success: 'Tetapan berjaya dikemas kini.',
  settings_password_mismatch: 'Kata laluan tidak sepadan.',
  admin_management_title: 'Pengurusan Admin',
  admin_management_approve: 'Luluskan',
  admin_management_revoke: 'Batalkan',
  admin_management_no_admins: 'Tiada admin lain didaftarkan.',
  footer_contact: 'Hubungi Paderi: Gurukal Kumarah',
  footer_rights: 'Hak cipta terpelihara.',
  back_to_public: 'Kembali ke Paparan Awam',
};

const DICTIONARIES: Record<Language, TranslationDict> = { EN, TA, BM };

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  language: 'EN',
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('EN');

  const t = useCallback(
    (key: string): string => {
      const dict = DICTIONARIES[language];
      return dict[key] ?? key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextValue {
  return useContext(LanguageContext);
}
